import type { Plan } from './components/PlanCard';

export const plans: Plan[] = [
  {
    id: 'free',
    name: 'Free',
    tagline: 'Perfect to get started',
    monthlyPrice: 0,
    annualPrice: 0,
    features: [
      { text: '50 DMs per month', included: true },
      { text: '1 automation sequence', included: true },
      { text: 'Basic analytics', included: true },
      { text: '1 social account', included: true },
      { text: 'AI smart replies', included: false },
      { text: 'Priority support', included: false },
      { text: 'Custom branding', included: false },
      { text: 'API access', included: false },
    ],
    ctaLabel: 'Get Started Free',
    ctaVariant: 'outline',
  },
  {
    id: 'pro',
    name: 'Pro',
    tagline: 'For serious creators',
    monthlyPrice: 29,
    annualPrice: 23,
    badge: 'Most Popular',
    badgeType: 'popular',
    featured: true,
    features: [
      { text: '2,000 DMs per month', included: true },
      { text: '20 automation sequences', included: true },
      { text: 'Advanced analytics', included: true },
      { text: '5 social accounts', included: true },
      { text: 'AI smart replies', included: true },
      { text: 'Email support', included: true },
      { text: 'Custom branding', included: false },
      { text: 'API access', included: false },
    ],
    ctaLabel: 'Start Pro Trial',
    ctaVariant: 'primary',
  },
  {
    id: 'business',
    name: 'Business',
    tagline: 'For teams & agencies',
    monthlyPrice: 79,
    annualPrice: 63,
    badge: 'Best Value',
    badgeType: 'best',
    features: [
      { text: 'Unlimited DMs', included: true },
      { text: 'Unlimited sequences', included: true },
      { text: 'Custom analytics', included: true },
      { text: 'Unlimited social accounts', included: true },
      { text: 'AI smart replies', included: true },
      { text: '24/7 priority support', included: true },
      { text: 'Custom branding', included: true },
      { text: 'Full API access', included: true },
    ],
    ctaLabel: 'Start Business Trial',
    ctaVariant: 'outline',
  },
];
